api:
  stage: 'http://stage2.youhuiin.com'
  apis: 'http://apis.youhuiin.com/api'
provider:
  other: 0
  weibo: 1
  tqq: 2
  qq_connect: 3
omniauth:
  weibo:
    key:
    secret:
  tqq:
    key:
    secret:
  qq_connect:
    key:
    secret:
  wechat:
    key:
    secret: 
alipay:
  pid:
  key:
  seller_email:
