default_url_options:
  host: 'localhost'
default_image_url:
  product:
    small: http://111.207.166.195/fileupload/img/product/default/default_120x0.jpg
    middle: http://111.207.166.195/fileupload/img/product/default/default_320x0.jpg
  user: http://itoo.yintai.com/fileupload/img/user-logo-default.gif
payment_code:
  alipay: 25
  wxpay:  28
alipay_notify_url: http://111.207.166.195/api/payment/notify
wx:
  appid: "wx69c8e957bfd6d041"
  appsecret: "3ce01d91e45c244151ec5c27dc94ed6a"
  backdomain: "freebird.ngork.com"
  token: "cnjobs"