omniauth:
  weibo:
    key: '1979938254'
    secret: '6970002e4a00849c10dbbd9b9054523e'
  tqq:
    key: '801450633'
    secret: '01f2081d530ecbe15e9097dd02cee160'
  qq_connect:
    key: '100382932'
    secret: '8acc22a900a6cf3a144c4e7364dafa78'

  wechat:
    key:  wxec92040268f6acec
    secret: d3bd5d1068c0df6bcde1c757702e1647

alipay:
  pid: '2088011888580823'
  key: 'n4q74v8r3bnhzsbthx0yf3g1ama9mntm'
  seller_account: 'maoym@intime.com.cn'

default_url_options:
  host: 'i.intime.com.cn'


default_image_url:
  product:
    small: http://irss.oss.aliyuncs.com/fileupload/img/product/default/default_120x0.gif
    middle: http://irss.oss.aliyuncs.com/fileupload/img/product/default/default_320x0.gif
  user: http://irss.oss.aliyuncs.com/fileupload/img/user-logo-default.gif


payment_code:
  alipay: 25
  wxpay:  29
  imswxpay: 30

alipay_notify_url: http://42.120.63.90/api/payment/notify
alipay_pc_notify_url: http://42.120.63.90/api/payment/notify2

api:
  stage: 'http://localhost'
  apis: 'http://42.120.63.90/api'
  imsapi: 'http://42.120.63.90/ims'
domain: 'intime.com.cn'
elasticache:
  host: '26497daec78911e3.m.cnhzalicm10pub001.ocs.aliyuncs.com'
  port:  '11211'
  username: '26497daec78911e3'
  password: 'selinadu_123'
  

elasticsearch_url: "http://10.161.218.70:9200"
fileserver_host: "http://irss.oss.aliyuncs.com/ims"
wx:
  appid: wx4b1d3b7765ce45d1
  appsecret: cc8219601137db20d7cf2fa94efc8fd6
  paysignkey: 5fYYsQSHaEsZbcbf76GKyim7loJUxSPKRUqUbgC7jAFzDtslhiWF44tzXiNrv9QzhI9Yl0IPE7QVUuuODU8v0qsKAAgaHNwbuW1MoPicV1z1xg85rxNAYo0BcsYBt5NE
  parterid: 1218686401
  parterkey: a8d319ce4a9c358293b97b1df51d531e
  backdomain: "42.121.255.198"
  notifydomain: "42.120.63.90"
  open_id: ""
